# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410e6d3c674a0f86d1c4ec866390b1750960d543a4566f97b0c91031ab0dfbfe54a2d9b0b81ae25ad4c9f42e639bed9f582c70590f8caa412150051f5b8af7c4

test:
  secret_key_base: 5d4e3314961c6f2b91b42d3b4298b02516fd48d6713ebc181f1d71285b7f773ac82db55877cf7bc4ee19892082abf25a1a3e9a43bb75e01e3cb3d3a8ba73227e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
